server:
  port: 8080

keycloak:
  introspection-uri: "${KEYCLOAK_URL}/realms/pet-adoption/protocol/openid-connect/token/introspect"
  client-id: "pet-adoption"
  client-secret: "${KEYCLOAK_CLIENT_SECRET}"

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/pet-adoption
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**, /api/auth/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}