server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: ${db-url}
    username: ${db-username}
    password: ${db-password}
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

keycloak:
  server-url: ${keycloak-url}
  realm: ${keycloak-realm}
  admin-client-id: ${keycloak-admin-client-id}
  admin-client-secret: ${keycloak-admin-client-secret}
  gateway-client-id: ${keycloak-gateway-client-id}
  gateway-client-secret: ${keycloak-gateway-client-secret}
